language: generic
services:
  - docker

cache:
  directories:
    - $HOME/.ccache

git:
  quiet: true

env:
  global:
    - CCACHE_DIR=$HOME/.ccache
    - ROS_REPO=main
  matrix:
    - ROS_DISTRO=kinetic
    - ROS_DISTRO=melodic
    - ROS_DISTRO=noetic

install:
  - git clone --quiet --depth=1 -b master https://github.com/ros-industrial/industrial_ci.git .industrial_ci

script:
  - .industrial_ci/travis.sh
